### ISSUE TITLE
Record user statistics for the webpage

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#1029]
Do we have any data on user statistics for the web pages?
There are a few data points that would be useful to have. For instance
- Which pages do users visit most? Maybe some of these should be given more attention.
- Do readers check the corresponding core files when they look at the foundation file?
- Where do people go from the main page?
- How many users do we have on a day-to-day basis?

**Comment by VojtechStep** [comment]
I have some experience with https://www.goatcounter.com/ , so we can look into that in the future.

**Comment by fredrik-bakke** [comment]
> I have some experience with https://www.goatcounter.com/ , so we can look into that in the future.

I.e. next week :)
