### ISSUE TITLE
Clean up git history

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#1068]
### Goals
- [ ] Rewrite history on master crediting `fernabnor` and `louismntnu` in too many files #665 
	- [ ] Files they contributed to: `posets`, `preorders`, ...
- [ ] Rewrite history on master about Egbert vs. Gregor
- [ ] Squash commits in february 2023
   - [ ] The commits are currently interleaved. Maybe a good strategy is to first sort them, and then squash
- [ ] Fix MAlonzo commit by ivankobe and deletion by MatejJazbec #212 
- [ ] Fix website commit by Jonathan
- [ ] Chore tagging

**Comment by EgbertRijke** [comment]
I understand the first and fourth point, but:
- What does "Egbert vs. Gregor" refer to?
- Why do the commits in february 2023 have to be squashed?
- What is the problem with the commits done by Jonathan?

I'm also curious why it is desirable to change the git history. What are the side effects of doing so?

**Comment by VojtechStep** [comment]
"Egbert vs Gregor" refers to #757 being squashed, so Gregor is now a listed coauthor on over 120 files which he didn't touch.
The other two I'm not so sure about.

The intention behind changing the git history is to more appropriately attribute work on the webpage, and making the "Recent changes" section more relevant: prune out renaming/mechanical refactorings by using the `chore:` convention

**Comment by EgbertRijke** [comment]
That work was a collaboration with Gregor. It is true that I ended up doing most of the formalization work, but we met weekly over the summer and discussed and planned our progress together. While he didn't "touch" those files, he was certainly involved.

I don't think this history should be rewritten.

**Comment by fredrik-bakke** [comment]
> - What is the problem with the commits done by Jonathan?

The whole website was at one point merged into master and then removed again, which doesn't look that good, and overshadows Jonathan's  contributions in his contribution statistics.

**Comment by EgbertRijke** [comment]
I'm worried that if we change the git history, then people might be working with different/incompatible versions of the repository. 

I'm also quite uncomfortable with the whole idea of rewriting the history. Why do we know better than the people at the time who was involved? I think the "Egbert vs Gregor" case clearly shows that we might be making big mistakes when we start editing the git history.

At the time of the pull request, we made the decision that a pull request was coauthored by certain people. The attribution reflects the conventions at that time. I feel fairly strongly that we should not change that, and that rewriting history is dangerously wielding too much power.

So I might not be on board with this.

**Comment by fredrik-bakke** [comment]
I disagree strongly. I think it is an erroneous argument that because something inaccurate was suggested, none of the suggestions are merited.

**Comment by EgbertRijke** [comment]
The fact that I used an illustrative example does not discredit my discomfort with the idea of rewriting history.

**Comment by fredrik-bakke** [comment]
While I do wish to respect feelings, they are rarely as actionable as reason and make it difficult to respond with anything but feeling in return.

**Comment by EgbertRijke** [comment]
> While I do wish to respect feelings, they are rarely as actionable as reason and make it difficult to respond with anything but feeling in return.

This statement that "feelings aren't actionable" does not line up well with your statement on Discord, where you explain your motivation to push for rewriting the git history. I quote:

> The changes amounted to 201 different formalization files being edited, which my colleagues are now credited on the website for. This I am a bit embarrassed about.

Essentially what I hear you say in these two statements combined is that your perspective counts and mine doesn't. It just seems that you're trying anything to push your will through, and it is unpleasant.

It seems that there is a clear consensus among our colleagues that editing the git history is a bad idea. The git history consists of snapshots of the contributions that were made, from the moment that they were merged into the library, subject to the conventions at the time. This is how it should be. They are automatic and objective. Editing them makes the subjective, and it looses the integrity of the git history.

It should not be done, and I am now fully against editing the git history of agda-unimath.

**Comment by EgbertRijke** [comment]
I would like to add that I am aware that we have been disagreeing a lot over the past couple of days, but I am not forgetting that your suggestions for the library come from a good place. Even if I disagree with a particular suggestion, I know that you are taking care of the library the best you can and I am sorry that we have been at odds so much lately. I am sure we can resolve these things.
