### ISSUE TITLE
Attributions for "100 theorems"

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#1203]
If we are to give credit to the original formalizers of the "100 theorems" theorems, we need to know who they are.

For easy reference, the agda-unimath page on "Formalizing 100 Theorems":
- https://unimath.github.io/agda-unimath/literature.100-theorems.html

## The List
Here's a~n incomplete~ list, please update it or comment with additional information.

- [3. The Denumerability of the Rational Numbers](https://www.cs.ru.nl/~freek/100/#3), Fredrik Bakke
- [11. The Infinitude of Primes](https://www.cs.ru.nl/~freek/100/#11), Egbert Rijke
- [25. Schröder–Bernstein Theorem](https://www.cs.ru.nl/~freek/100/#25), Elif Uskuplu
- [44. The Binomial Theorem](https://www.cs.ru.nl/~freek/100/#44), Egbert Rijke
- [60. Bezout's Lemma/Theorem](https://www.cs.ru.nl/~freek/100/#60), Brian Lu (blu-bird)
- [63. Cantor's Theorem](https://www.cs.ru.nl/~freek/100/#63), Egbert Rijke
- [69. Greatest Common Divisor Algorithm](https://www.cs.ru.nl/~freek/100/#69), Egbert Rijke
- [74. The Principle of Mathematical Induction](https://www.cs.ru.nl/~freek/100/#74), Egbert Rijke
- [80. The Fundamental Theorem of Arithmetic](https://www.cs.ru.nl/~freek/100/#80), Victor Blanchi
- [91. The Triangle Inequality](https://www.cs.ru.nl/~freek/100/#91), malarbol

**Comment by fredrik-bakke** [comment]
Thank you! I'll review the remaining ones when I find the time

**Comment by EgbertRijke** [comment]
Bezout's lemma was added by blu-bird. He is currently not credited on either page on the Bezout lemma (for natural numbers, for integers), which is not great.

**Comment by EgbertRijke** [comment]
Cantor's theorem was added by me, but is also not credited on the page. This is quite a big disadvantage of the automated crediting, given that it doesn't keep track when contents are moved to different files.

**Comment by fredrik-bakke** [comment]
Definitely not good!
