### ISSUE TITLE
There exist hydrocarbons with carbon atoms with 4 carbon-carbon bonds 

### ISSUE THREAD

**Issue by MadeleineBirchfield** [UniMath/agda-unimath#234]
The cumulenes are a class of hydrocarbons with at least three consecutive pairs of double bonds between neighbouring carbon atoms. As a result, the carbon atoms in the middle of the chain of double bonds each have 4 carbon-carbon bonds. 
https://en.wikipedia.org/wiki/Cumulene
Another example of a class of hydrocarbons with a carbon atom with 4 carbon-carbon bonds is any alkyne that is not acetylene:
https://en.wikipedia.org/wiki/Alkyne
If Amelia is correct that the current definition of hydrocarbon only allows carbon atoms to have at most 3 carbon-carbon bonds in https://github.com/UniMath/agda-unimath/issues/232#issuecomment-1175563733, than the current definition excludes the cumulenes and the alkynes.

**Comment by EgbertRijke** [comment]
I think the current definition does not exclude these cases. It only excludes the case where a carbon atom C is bonded to a single other carbon atom C' by 4 bonds.

**Comment by EgbertRijke** [comment]
There is another way to avoid this case: The condition that there must be at least one hydrogen atom present in the hydrocarbon also implies (by the connectedness assumption) that there can not be two carbon atoms in the molecule with a quadruple bond between them.

**Comment by MadeleineBirchfield** [comment]
Going to close this issue since it doesn't seem to be a problem anymore.
