### ISSUE TITLE
Automated checks for module indexing

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#448]
As demonstrated by #447, I think for the scalability of this project, there should be a job in the GitHub workflow that checks that the appropriate module references are in place, as it's a recurring and tedious job to manually do this.

What I have in mind is a script that checks the following:
- [x] For every appropriate subdirectory, check that there is a `.lagda.md` file with the name of that subdirectory.
- [x] For every file in that directory, check that it defines a module named `supdirectory-name.[...].subdirectory-name.file-name` (given that nested namespaces are allowed)
- [x] In the subdirectory `.lagda.md` file, check that every `.lagda.md` file in the subdirectory is imported
- [x] Check that each import is public
- [x] Check that the imports in it are sorted alphabetically
- [x] Check that there is a header in `SUMMARY.lagda.md` with a reference to every subdirectory's `.lagda.md` file
- [x] Check that this header is the title inside that subdirectory's `.lagda.md` file
- [x] Check that every file in that subdirectory is referenced in `SUMMARY.lagda.md` under that subdirectory
- [x] Check that the name used to reference that file is the title inside the file
- [x] Check that the entries are sorted in alphabetic order (either by the title in the file, or the name of the file)

**Comment by jonaprieto** [comment]
Agree. You meant having a new job in the GitHub workflow that checks, as you said. We can have it better as an intermediate step in the job check-docs. I would expect a script that generates the file before building the website (file path should be `docs/SUMMARY.md` and add the entry in the file `.gitignore`.

**Comment by fredrik-bakke** [comment]
Thank you for the correction, I've edited the issue.
Are you suggesting the `SUMMARY`-file's index be autogenerated instead of manually maintained and checked? That does sound like an improvement over my suggestion.

**Comment by jonaprieto** [comment]
> Thank you for the correction, I've edited the issue. Are you suggesting the `SUMMARY`-file's index be autogenerated instead of manually maintained but automatically checked? That does sound like an improvement over my suggestion.

Exactly.
