### ISSUE TITLE
Support for Agda code blocks in Dark themes

### ISSUE THREAD

**Issue by jonaprieto** [UniMath/agda-unimath#507]
Reading Agda blocks using a Dark theme (which is nice for your eyes) is hard.
The changes should be made in `theme/Agda.css`, preferably using vars from `theme/css/variable.css`. Ask if you want more details to help here.

![image](https://user-images.githubusercontent.com/1428088/224957427-81117940-73e3-4a04-af43-dc7d4fc7d2db.png)

**Comment by ncfavier** [comment]
AFAICT there's a conflict on Agda identifiers between

- https://github.com/UniMath/agda-unimath/blob/321459b24cde393d3350758887cf6641c4ace9bb/theme/css/chrome.css#L8-L13
  which says that all links should have the link colour
- https://github.com/UniMath/agda-unimath/blob/321459b24cde393d3350758887cf6641c4ace9bb/theme/Agda.css#L66-L68
  and similar rules that dictate what colour Agda identifiers should have

For unvisited links the first rule wins, but for visited links the second rule wins. Presumably the second rule should always win, and the Agda colours should be adjusted depending on the chosen theme?
