### ISSUE TITLE
Some files erroneously end the details block with `<details>` instead of `<\details>`

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#523]
Some files erroneously end the details block with `<details>` instead of `<\details>`. However, I don't know the regular expression to search and replace this throughout the library. All occurrences of `<details>` followed by a new line character should be replaced by `<\details>`

**Comment by jonaprieto** [comment]
I got this (using .*<details>.*<details>.*):

```
src/group-theory/function-commutative-monoids.lagda.md
src/ring-theory/function-rings.lagda.md
src/group-theory/function-monoids.lagda.md
src/group-theory/dependent-products-semigroups.lagda.md
src/group-theory/dependent-products-abelian-groups.lagda.md
src/group-theory/function-semigroups.lagda.md
src/group-theory/function-abelian-groups.lagda.md
src/group-theory/dependent-products-groups.lagda.md
src/group-theory/dependent-products-monoids.lagda.md
src/structured-types/function-magmas.lagda.md
src/group-theory/function-groups.lagda.md
src/group-theory/dependent-products-commutative-monoids.lagda.md
```
This is easy to fix.

**Comment by fredrik-bakke** [comment]
FYI, it should be `</details>` with a forwards slash `/`.

**Comment by jonaprieto** [comment]
Oh, I accidentally found the other issue with the regex I used above. So there are two issues.
