### ISSUE TITLE
Pages are not listed alphabetically anymore

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#541]
Since we switched to the custom titles, entries starting with "The" are listed among pages starting with "T". This is wrong. For example, the page on the binomial theorem should be among the pages starting with "B", not with "T" even though the title of the page is "The binomial theorem".

**Comment by fredrik-bakke** [comment]
Thanks for bringing this up again. I see two ways we can resolve this issue.

1. Ignore "the" at the start of titles, and sort based on the rest of the string.
2. Sort based on module name.

Which one do you have in mind?
Personally, I miss having the module names visible in the index, as it makes things more similar to what I see in my IDE. So although the first solution is the more obvious one, I don't think I would personally mind the second solution if we also got the module names back.

**Comment by EgbertRijke** [comment]
My preferred solution would be that the files are sorted based on module names, but the custom titles are displayed for better readabiliby and to make the table of contents look nicer/friendlier.
