### ISSUE TITLE
Executable `scripts/remove_extra_blank_lines.py` not found

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#551]
In #549 @ElifUskuplu reported that `make pre-commit` gave her the following error:

```
Executable `scripts/remove_extra_blank_lines.py` not found
```

**Comment by fredrik-bakke** [comment]
Thanks for filing the issue!

Looking at her error messages, it seems that indeed none of the files in `scripts` were found. I suspect that perhaps the root directory is not set properly. I can take a closer look at this later when I'm at a computer. 🙂

**Comment by fredrik-bakke** [comment]
Elif mentioned in #569 that this was an issue with her git setup and that the problem has been resolved.
