### ISSUE TITLE
`make-precommit` sorting imports doesn't work properly

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#651]
For example, it didn't sort the imports here:
https://unimath.github.io/agda-unimath/finite-group-theory.transpositions-standard-finite-types.html

**Comment by EgbertRijke** [comment]
Never mind! I spotted that the `<details>` block wasn't closed properly.

**Comment by fredrik-bakke** [comment]
Actually, the script shouldn't fail silently when there is an opening and no closing tag I think. Thanks for the report!

**Comment by fredrik-bakke** [comment]
Turns out there are 7 files with this error:

**Comment by fredrik-bakke** [comment]
Turns out there are 7 files with this error:

```text
src/order-theory/homomorphisms-large-meet-semilattices.lagda.md
src/order-theory/closure-operators-large-posets.lagda.md
src/finite-group-theory/transpositions-standard-finite-types.lagda.md
src/trees/fibers-directed-trees.lagda.md
src/order-theory/large-subframes.lagda.md
src/commutative-algebra/poset-of-ideals-commutative-rings.lagda.md
src/synthetic-homotopy-theory/dependent-universal-property-pushouts.lagda.md
```
This will be automatically detected with my next PR.
