### ISSUE TITLE
Detect ill-formed import blocks

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#652]
This file had an ill-typed `<details>` block which wasn't closed, but it wasn't detected by `make pre-commit`.

https://unimath.github.io/agda-unimath/finite-group-theory.transpositions-standard-finite-types.html

**Comment by fredrik-bakke** [comment]
Ah, sorry, didn't see that you filed a second issue. As I mentioned in #651, this will be fixed by an upcoming PR.

**Comment by fredrik-bakke** [comment]
I want to be clear about what is considered a bug and not. I don't think this is a bug, as the CI was not previously expected to detect when the user had misformatted their markdown in this way. Instead, this is a new feature to add to the CI. The bug would be that some files are ill-formatted, but that's not what this issue focuses on.

**Comment by EgbertRijke** [comment]
I'm sorry for the confusion. I thought this was something the CI was supposed to do:)

**Comment by fredrik-bakke** [comment]
Understandable! It would be natural to have this feature from the start. But alas, we did not think of it. 😅
