### ISSUE TITLE
Inconsistent use of `python` vs `python3`

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#672]
The documentation and various `make` targets are inconsistent between using `python` vs `python3` and `pip` vs `pip3`. This can lead to confusion as these don't necessarily point to the same executables. For instance if the user installs the required packages with `pip` and then runs `make pre-commit`, it is not guaranteed that the proper requirements are installed. We should decide on using either one, and use that consistently everywhere.

**Comment by VojtechStep** [comment]
I'd suggest sticking to `python3`, adding a shebang to the `update_contributors.py` script (since that's supposed to be runnable), and using `python3 -m pip` for pip (I'm not sure how standard the `pip3` name is).
I can make the changes in the evening.

**Comment by fredrik-bakke** [comment]
That would be amazing, thank you!

**Comment by VojtechStep** [comment]
I couldn't find any mention of just `python` or `pip3` anywhere, am I missing something? The Makefile has just one relevant rule, and it references `python3`.

**Comment by fredrik-bakke** [comment]
Thanks for doing this!
Here are the places I think you missed:
- `python` is used in three places in `.vscode/tasks.json`.
- `pip` is referenced in `.github/workflow/ci.yaml`, `.github/workflow/pages.yaml`, and `HOWTO-INSTALL.md`

**Comment by VojtechStep** [comment]
Oh, right, I forgot ripgrep doesn't search directories with leading `.` by default, I'll take a closer look 👌
