### ISSUE TITLE
`make website` shouldn't type check the library

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#679]
This is inconvenient as it makes the process of building the website quite a bit longer. There are other steps in the process that ensure the library is type checked, so why insert it here as well? Having a library that type checks should not be necessary to build the website.

**Comment by EgbertRijke** [comment]
I think it is ok. If the library hasn't typechecked yet, then it is good to type check the library. If it has already type checked, then it will only take a few seconds to recognize that it was already done.

**Comment by fredrik-bakke** [comment]
Never mind, the type checking is also used for syntax highlighting.

**Comment by jonaprieto** [comment]
Just to let you know, we are only scope-checking the code when building the website. We only type check on the ci workflow. The relevant part of the website workflow is the env variable AGDAHTMLFLAGS. Its default value is:

```
--html --html-highlight=auto --html-dir=docs --only-scope-checking
```
