### ISSUE TITLE
The double white-space remover is too aggressive on the markdown part

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#696]
In markdown, sometimes you want to add double white space in order to add a line break. For example, if you write a list

```md
1. One item

   Something to say further about it
2. Second item
3. Third item
```

The most markdown renderers will add extra space between all list items. This is not always desirable. One way to mitigate this problem is to write the list in the following way:

```md
1. One item  
   Something to say further about it
2. Second item
3. Third item
```

Note that there are two additional spaces after "1. One item  ". This double white-space tells markdown to add a line break, because the line break that you see in the code actually doesn't suffice to add it. However, our double white-space remover removes these, so it is impossible to use this solution. My suggestion is to let the double white-space remover act only within agda code blocks.

**Comment by fredrik-bakke** [comment]
Thanks for the report! The double whitespace remover should only apply to Agda code. I think what is interfering here is either the trailing whitespace pre-commit hook, or the corresponding vscode functionality. Some of our other custom hooks may also be removing these inadvertently. What we can do to mitigate this is to disable the trailing whitespace removers, make sure that our own hooks only remove trailing whitespace in Agda code, and rely on the markdown formatter alone to format the markdown code properly.

**Comment by fredrik-bakke** [comment]
[Here is an alternative solution](https://stackoverflow.com/a/59858327/2692801) for you that avoids using trailing whitespace. I think it is bad practice to use trailing whitespace because it is not visible to a reader of the code that it is there.

I'm going to close this issue, given the alternative solution, but feel free to reopen it if you disagree.
