### ISSUE TITLE
Standard sequential colimit and its functoriality

### ISSUE THREAD

**Issue by VojtechStep** [UniMath/agda-unimath#868]
The standard sequential colimit of a sequential diagram can be constructed from standard coequalizers of the uncurried sequence.
For symmetry with other (co)limits in the library, it would be nice to show that construction of the standard sequential colimit is functorial in the diagram, i.e. morphisms of sequential diagrams induce maps of standard sequential colimits, and it preserves identity and composition.

**Comment by fredrik-bakke** [comment]
It would also be nice to record a file on transfinite composition as part of this issue, because transfinite composition is cool :)

**Comment by EgbertRijke** [comment]
Transfinite composition is cool, but it should be noted that this is not general transfinite composition. In a file about transfinite composition we should expect a treatement of general transfinite composition, i.e., using a diagram indexed by an ordinal.
