### ISSUE TITLE
Identity system on implicit Pi types

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#925]
As suggested in #877, we should have direct infrastructure for implicit Pi-types, instead of converting implicit Pi-types to explicit Pi-types each time we try to construct an identity system over an implicit Pi-type. I'll mark this as a general issue, because it would probably be best to do this separately and hunt for all the occurrences `equiv-explicit-implicit-Π` in constructions of identity systems for implicit Pi-types.

**Comment by fredrik-bakke** [comment]
Turns out I did this one a month ago. You can find it in `foundation.equality-dependent-function-types` as `is-torsorial-Eq-implicit-Π` :)

**Comment by EgbertRijke** [comment]
Did you also hunt for those occurrences `equiv-explicit-implicit-Π` in constructions of identity systems involving implicit Pi-types, or should this PR still be open until we complete this task as well?

**Comment by fredrik-bakke** [comment]
Yes I did, the only occurence was in the file about isomorphisms of rings. Actually, replying to this gave me an idea. We should definitively show torsoriality of multivariable (implicit) homotopies. I'll do that in my open PR.

**Comment by EgbertRijke** [comment]
Great! Then this Issue can indeed be closed.
