### ISSUE TITLE
The equivalences on hom-sets in adjunctions of large (pre)categories go the unnatural way

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#926]
During my formalization of the abelianization adjunction in #877 I noticed that the equivalences on hom-sets in adjunctions go the unnatural way: Given `F : C -> D` with right adjoint `G : D  -> C`, the equivalence goes

```text
  hom C X (G Y) <~> hom D (F X) Y
```

However, when we're constructing a left adjoint equipped with a unit, then this equivalence will be the inverse equivalence of precomposition by the unit. It would be more natural to have this equivalence the other way around, so that the equivalence on hom-sets can really be precomposition by the unit. Similarly, if we would be constructing a right adjoint equipped with a counit, we would like to construct it as postcomposition with the counit. Again it would go the other way.

In #877 I sticked with the current formulation of adjunction, because there are still some other PRs about category theory open and I didn't want to create any trouble. But I think it would be better if we reverse the direction of this equivalence before we formalize too many adjunctions.

**Comment by fredrik-bakke** [comment]
If you're referring to my prs, then they do not touch adjunctions.
