### ISSUE TITLE
Investigate memory usage when typechecking the whole library

### ISSUE THREAD

**Issue by VojtechStep** [UniMath/agda-unimath#985]
The CI workflows started running out of memory at the end of typechecking the library (the last line of the logs is that it's checking `everything.lagda.md`).

Examples of failed jobs:
- MacOS: https://github.com/UniMath/agda-unimath/actions/runs/7232860795/job/19707495899
- Ubuntu: https://github.com/UniMath/agda-unimath/actions/runs/7186165597/job/19570972093

The runners themselves should have enough memory (7 GB for Ubuntu and 14 GB for MacOS according to [the docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)), so for now we probably can bump Agda's internal memory limit, but it'd still be best to investigate why we need 4 GB of RAM to typecheck the library.

**Comment by fredrik-bakke** [comment]
Agda does have some functionality for measuring the type-checking performance of a formalization. It would be nice regardless to log this on the master branch, although perhaps the runners aren't designed for performance testing.

**Comment by fredrik-bakke** [comment]
This is not an issue we have much power over. After #1031 we at least record memory usage over time. But in the end, we are subject to the limitations of what Agda can and can't handle.
